name: "LOC Graph Action"
description: "Generate an SVG chart of Lines of Code over time from commit history"
author: "Maxim Oransky"
branding:
  icon: 'trending-up'
  color: 'green'
inputs:
  output_json:
    description: "Path to cached LOC history JSON"
    default: ".github/loc_history.json"
    required: false
  fallback_theme:
    description: "Theme for fallback SVG (light or dark)"
    default: "light"
    required: false
  date_format:
    description: "Date format for multi-day projects (Python strftime)"
    default: "%d.%m.%Y"
    required: false
  time_format:
    description: "Time format for same-day commits (Python strftime)"
    default: "%H:%M"
    required: false
runs:
  using: "composite"
  steps:
    - name: Ensure full git history
      shell: bash
      run: |
        if [ "$(git rev-parse --is-shallow-repository)" = "true" ]; then
          git fetch --unshallow --tags
        fi

    - name: Install cloc
      shell: bash
      run: |
        sudo apt-get install -y cloc --no-install-recommends

    - name: Run LOC graph generator
      shell: bash
      run: |
        FALLBACK_THEME="${{ inputs.fallback_theme }}" \
        DATE_FORMAT="${{ inputs.date_format }}" \
        TIME_FORMAT="${{ inputs.time_format }}" \
        python3 "${GITHUB_ACTION_PATH}/scripts/loc_graph.py"

    - name: Commit artifacts if changed
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ".github/loc-history.svg" ".github/loc-history-light.svg" ".github/loc-history-dark.svg" "${{ inputs.output_json }}" || true
        if ! git diff --cached --quiet; then
          git commit -m "Update LOC graph [skip ci]"
          git push
        fi
